### ISSUE TITLE
Control Panel dissapears when you clikc Check price on https://demo-ui.erpya.com/ and go back

### ISSUE THREAD

**Issue by jabo6311** [adempiere/adempiere-vue#1616] opened 2022-02-18 14:30 UTC
#### Steps to reproduce

1. click Check price on Control Panel
2. Go back
3. Control Panel is missed

#### Screenshot or Gif（截图或动态图）
**![image](https://user-images.githubusercontent.com/33498993/154700458-df2cb978-346f-48b5-af4c-8e52a5599fad.png)**

#### Expected behavior
What I expect to happen is Control Panel does not disappear when I go back from check price

#### Other relevant information
- Your OS: linux mint
- Web Browser: brave
- Node.js version: N/A
- adempiere-vue version: N/A

#### Additional context
Fix it as soon as possible

**Comment by elsiosanchez** [comment] 2022-02-18 18:40
Greetings @jabo6311  When entering the Price Finder form, the menu and tabs of the application are hidden

If you want to enable the menu and the tabs of the windows you have to go to User / Configuration there you can find a check where you can make the menu visible

Next I leave a Gif with the steps to reproduce

#### Gif
![dashboard](https://user-images.githubusercontent.com/45974454/154742236-c496f00f-0c92-43e5-9005-840fe8da4d83.gif)


#### Link to minimal reproduction (Demo）
https://demo-ui.erpya.com/#/login

#### Other relevant information
  Your OS: Debian 9
  Web Browser: Chrome
  Node.js version: v 14.18.0
  adempiere-vue version: v 4.4.0

#### Note
The behavior of that form was requested by @yamelsenih  since that form is only for price reader use

**Comment by elsiosanchez** [comment] 2022-02-18 18:45
@jabo6311  If the reason you opened this issue is resolved, please close it.

**Comment by jabo6311** [comment] 2022-05-16 21:57
ok

**Closed as completed** 2022-05-16 21:57 UTC
